Ink multisig milestone 1 delivery
use-inkubator/Grant-Milestone-Delivery pull request #4
Opened 2023-06-23 19:59 UTC by camimancusi

2023-06-27 08:57 UTC, mike1729 requested changes

2023-06-27 08:57 UTC, mike1729 commented on deliveries/ink_contract_multi-sig-1.md
> +| 2. | Technical Specs Document  | https://github.com/protofire/ink-multisig/blob/Milestone-1/docs/Contract%20Pallets%20Multisig%20Implementation_Backendless%20Architecture%20Document.pdf | |
In your application you declared that you'll conduct a research of existing implementations: https://github.com/use-inkubator/Ecosystem-Grants/blob/master/applications/ink_contract_multi-sig.md?plain=1#L28, so I expect that in your technical document you will provide a summary of this research, a discussion on pros and cons and argument for the design you choose.
You also declared that you will provide a description on the interoperability of your contracts with other contracts.
Finally, you provide a list of methods of contracts and an example of user interaction but there are no details on eg. what values are possible, when functions succeed and when not.
Please update your technical document with the above informations.

2023-07-12 10:36 UTC, TtomaS7 commented on deliveries/ink_contract_multi-sig-1.md
> +| 2. | Technical Specs Document  | https://github.com/protofire/ink-multisig/blob/Milestone-1/docs/Contract%20Pallets%20Multisig%20Implementation_Backendless%20Architecture%20Document.pdf | |
hey!
What is about sharing the range of possible values, success conditions, and failure scenarios?

2023-07-13 15:23 UTC, 0xLucca commented on deliveries/ink_contract_multi-sig-1.md
> +| 2. | Technical Specs Document  | https://github.com/protofire/ink-multisig/blob/Milestone-1/docs/Contract%20Pallets%20Multisig%20Implementation_Backendless%20Architecture%20Document.pdf | |
Hey @TtomaS7! 
We have provided information on the specific errors that can be thrown by each callable function and the events they will emit. This aims to provide a comprehensive understanding of the behavior and potential outcomes when using these functions. Furthermore, as our frontend development progresses and we incorporate improvements to the contract, we are committed to providing extensive documentation that covers a wide range of potential scenarios. This will ensure that users have comprehensive guidance and support when interacting with our system, enabling them to make the most of its capabilities.

2023-07-14 12:11 UTC, TtomaS7 commented on deliveries/ink_contract_multi-sig-1.md
> +| 2. | Technical Specs Document  | https://github.com/protofire/ink-multisig/blob/Milestone-1/docs/Contract%20Pallets%20Multisig%20Implementation_Backendless%20Architecture%20Document.pdf | |
Sorry, but I don’t see new commits..may I know where is the provided information on the specific errors?

2023-07-14 12:20 UTC, 0xLucca commented on deliveries/ink_contract_multi-sig-1.md
> +| 2. | Technical Specs Document  | https://github.com/protofire/ink-multisig/blob/Milestone-1/docs/Contract%20Pallets%20Multisig%20Implementation_Backendless%20Architecture%20Document.pdf | |
Hi @TtomaS7 The updates addressing the specific errors have been committed to the code repository. You can find the provided information in the updated PDF document at this link: [Contract Pallets Multisig Implementation Backendless Architecture Document](https://github.com/protofire/ink-multisig/blob/Milestone-1/docs/Contract%20Pallets%20Multisig%20Implementation_Backendless%20Architecture%20Document.pdf).

2023-07-26 00:52 UTC, HCastano commented
@0xLucca Mike has been on vacation the last few weeks, but he'll take a look again soon!

2023-08-08 18:16 UTC, HCastano reviewed
Thanks for the submission. However the research docs and the contract need a bit of work

2023-08-08 18:16 UTC, HCastano commented on deliveries/ink_contract_multi-sig-1.md
> +2) Discovery POC Understanding Ink Smart Contracts
I don't understand who the audience of this document is.

Is the audience for new contract developers, developers new to ink!, people curious about ink!? It's unclear since the doc goes through a lot of different levels of abstraction.

What are the teachings you hoped to provide here?

2023-08-08 18:16 UTC, HCastano commented on deliveries/ink_contract_multi-sig-1.md
> +1) Overcoming Reentrancy and Circular Call Challenges in Polkadot Smart Contracts
Same here, I don't understand who this was written for

2023-08-08 18:16 UTC, HCastano commented on deliveries/ink_contract_multi-sig-1.md
> +3) Contract Pallet Multisig Implementation_Backendless Architecture Document
I was hoping this document would provide different approaches to a smart contract based multisig alongside all the associated trade-offs.

Did you explore any other solutions? If so can you add them to this document?

2023-08-08 18:16 UTC, HCastano commented on deliveries/ink_contract_multi-sig-1.md
> +| 3. | Multisig Smart Contract | https://github.com/protofire/ink-multisig/tree/Milestone-1/contracts | |
There's still a lot of `TODO` comments in the code. Can you instead track these using GitHub issues? This will ensure that these issues are more visible and their progress can be tracked.

There's also a lot of unnecessary comments.

E.g 

```rust
// Handle next_tx_id
let current_tx_id = self.next_tx_id;

AND

 // ink_storage::lazy::mapping::Mapping receives a reference, so we are passing a &transaction
self.txs.insert(current_tx_id, &tx);
```

Comments like this don't provide much value to the reader beyond what they can gleam from reading the code or the function signature

2023-08-08 18:16 UTC, HCastano commented on deliveries/ink_contract_multi-sig-1.md
> +| **0c.** | Testing and Testing Guide | https://github.com/protofire/ink-multisig/blob/Milestone-1/README.md | |
I would like to see more tests for the contract. Both units test and possible `ink_e2e` tests (or a few more TS tests showing the operation of the multisig)

2023-08-09 14:03 UTC, 0xLucca commented on deliveries/ink_contract_multi-sig-1.md
> +| **0b.** | Documentation | https://github.com/protofire/ink-multisig/blob/Milestone-1/README.md | |
We are working on it. We'll let you know as soon as its ready.

2023-08-09 14:05 UTC, 0xLucca commented on deliveries/ink_contract_multi-sig-1.md
> +| **0c.** | Testing and Testing Guide | https://github.com/protofire/ink-multisig/blob/Milestone-1/README.md | |
We chose to use a Makefile as our preferred build and testing tooling for several compelling reasons. Unlike other options, a Makefile consolidates all the essential tasks, commands, and scripts necessary for setting up our environment and executing tests within a single, well-organized document. This centralization streamlines our development process, ensuring consistency and making it easier for our team to comprehend and manage the workflow. This is crucial when preparing the environment for interacting with smart contracts and running tests, preventing errors that can arise from an incorrect execution sequence.

2023-08-09 14:23 UTC, 0xLucca commented on deliveries/ink_contract_multi-sig-1.md
> +1) Overcoming Reentrancy and Circular Call Challenges in Polkadot Smart Contracts
During the POC phase, we discovered an intriguing issue within Polkadot smart contracts. As a result, we created this document to explain the nature of this problem and presented a solution to ensure that the smart contracts operate as intended. This resource is not only valuable for our project but also has the potential to assist other developers facing similar challenges in their work.

2023-08-09 14:37 UTC, 0xLucca commented on deliveries/ink_contract_multi-sig-1.md
> +| **0c.** | Testing and Testing Guide | https://github.com/protofire/ink-multisig/blob/Milestone-1/README.md | |
@HCastano 

During the Proof of Concept (POC) phase, we intentionally focused on rapidly building and demonstrating the core functionality of the smart contract. This is why you might notice the presence of TODO comments in the code. These comments signify areas where further refinement and completion are required. However, I would like to clarify that our current deliverable was aligned with the POC phase, as described in our [application](https://github.com/use-inkubator/Ecosystem-Grants/blob/master/applications/ink_contract_multi-sig.md#1--discovery--proof-of-concept-poc-phase).

For the upcoming [Minimum Viable Product (MVP) phase](https://github.com/use-inkubator/Ecosystem-Grants/blob/master/applications/ink_contract_multi-sig.md#2--multi-sig-mininimum-viable-product-mvp), which is the next step in our project timeline, our plan encompasses a thorough polishing of the smart contract. This will involve addressing all TODO comments and ensuring a streamlined and well-documented codebase. Additionally, we'll be creating a comprehensive test suite to thoroughly validate the functionality of the smart contract.

Thank you for your valuable feedback, if you have any further questions feel free to ask.

2023-08-24 15:47 UTC, camimancusi commented
Hello @HCastano, could you take a look on the corrections that the team mentioned in our last comment?

2023-08-26 19:11 UTC, HCastano commented
@camimancusi Hey, I've been OOO recently. Will take a look next week 🙏

2023-09-12 14:22 UTC, HCastano approved these changes
Sorry for taking so long to review this. I appreciate that you guys have been moving
forward with development beyond this milestone 🙏

The contract and basic tests look good to me. I also see that testing has already been
expanded on `main`. For future milestones I would like to see the whole build and test
pipeline included as part of CI.

I'm still not super happy with the research documents and technical specification, but I
think we can make something work.

We can considering adding an additional milestone to fix the blog posts if that's
necessary.

For the research documents would it be possible for you guys to clean them up and post
them on Medium or equivalent? This way at least you'll have shared your work publicly and
hopefully somebody can find value from them.

I'd say that for the re-entrancy post that a few code samples could be added to better
demonstrate concepts to the readers. For the ink! exploration post I would tighten the
scope a bit and make it a bit more focused. I don't think that the doc should be that
wide in scope as I mentioned in a previous comment.

For the technical specification, I'd still like to see other approaches to _smart
contract multisigs_ added - not just a comparison to the Multisig pallet.

That said, I won't consider the blog posts blockers for acceptance of this milestone
given that a) the code you've delivered so far is fine and b) you've continued to improve
upon this for following milestones.

2023-09-12 15:52 UTC, DoubleOTheven commented
The docs are very well written. 

This is a NIT, but worth mentioning. In your [Smart Contracts](https://github.com/protofire/ink-multisig/blob/Milestone-1/docs/Discovery%20POC%20Understanding%20Ink%20Smart%20Contracts.pdf) section in the docs you mention that contracts are always untrusted and anyone can deploy one. It is possible that core developers could add pallet-contracts under permissions and require a governance body to vote before a contract is accessible, or only allow certain accounts to deploy one. It is up to the core developers to decide how they will use pallet-contracts. 

I see them as three categories:

* No Contracts
* Contracts and anyone can deploy (untrusted / the wild west)
* Permissioned Contracts (trusted or untrusted)

2023-09-19 15:16 UTC, GabrielCamba commented
> Sorry for taking so long to review this. I appreciate that you guys have been moving forward with development beyond this milestone 🙏
> 
> The contract and basic tests look good to me. I also see that testing has already been expanded on `main`. For future milestones I would like to see the whole build and test pipeline included as part of CI.
> 
> I'm still not super happy with the research documents and technical specification, but I think we can make something work.
> 
> We can considering adding an additional milestone to fix the blog posts if that's necessary.
> 
> For the research documents would it be possible for you guys to clean them up and post them on Medium or equivalent? This way at least you'll have shared your work publicly and hopefully somebody can find value from them.
> 
> I'd say that for the re-entrancy post that a few code samples could be added to better demonstrate concepts to the readers. For the ink! exploration post I would tighten the scope a bit and make it a bit more focused. I don't think that the doc should be that wide in scope as I mentioned in a previous comment.
> 
> For the technical specification, I'd still like to see other approaches to _smart contract multisigs_ added - not just a comparison to the Multisig pallet.
> 
> That said, I won't consider the blog posts blockers for acceptance of this milestone given that a) the code you've delivered so far is fine and b) you've continued to improve upon this for following milestones.

We're glad to tell you that we are already in the advanced stages of our project. Work on the front end is underway, and we are in the final stages of the smart contract development and testing. Additionally, to enhance user experience on the front end, we have integrated a subsquid for indexing blockchain data.

Regarding the articles, we value your suggestions and we will begin the process of publishing them for a wider audience. We aim to ensure that our content is both informative and accessible to all readers.

Thank you! :100:

2023-10-09 06:44 UTC, TtomaS7 commented
Hey team!

Here's the form for payment details: https://forms.gle/BUCKfygkiEvpdYna6.
Once you've filled it out, please let me know and be sure to specify what it pertains to; you can include the link to this PR delivery! Further details can be provided under the section: "Please describe which Milestone you have completed and attach the link to the Milestone delivery."

Should you have any questions, don't hesitate to ask. Thank you so much!

Important Note: PLEASE VERIFY YOUR ADDRESS, WHERE YOU WILL RECEIVE THE FUNDS, BEFORE FILLING OUT THE FORM!
For guidance on how to set up identity, refer to [this guide](https://support.polkadot.network/support/solutions/articles/65000181981-how-to-set-and-clear-an-identity).

2023-10-09 14:19 UTC, DiegoTorresborda commented
> Hey team!
> 
> Here's the form for payment details: https://forms.gle/BUCKfygkiEvpdYna6. Once you've filled it out, please let me know and be sure to specify what it pertains to; you can include the link to this PR delivery! Further details can be provided under the section: "Please describe which Milestone you have completed and attach the link to the Milestone delivery."
> 
> Should you have any questions, don't hesitate to ask. Thank you so much!
> 
> Important Note: PLEASE VERIFY YOUR ADDRESS, WHERE YOU WILL RECEIVE THE FUNDS, BEFORE FILLING OUT THE FORM! For guidance on how to set up identity, refer to [this guide](https://support.polkadot.network/support/solutions/articles/65000181981-how-to-set-and-clear-an-identity).

Hi Toma! Thanks for the confirmation!

2023-10-24 09:18 UTC, TtomaS7 commented
The payment sent!

https://polkadot.subsquare.io/treasury/child-bounties/19_460
You can claim it in 1 day, thank you!

2023-10-30 05:58 UTC, merged